const wordList = [
  { "word": "panda", "hint": "A cute black-and-white animal" },
  { "word": "rocket", "hint": "Flies into space" },
  { "word": "magic", "hint": "Something mysterious and amazing" },
  { "word": "pirate", "hint": "Sails the seas searching for treasure" },
  { "word": "robot", "hint": "A machine that can move or talk" },
  { "word": "cupcake", "hint": "A small cake with frosting" },
  { "word": "rainbow", "hint": "Colorful arc in the sky" },
  { "word": "cookie", "hint": "A sweet baked snack" },
  { "word": "turtle", "hint": "Moves slowly and has a shell" },
  { "word": "castle", "hint": "A big building where kings lived" },
  { "word": "dragon", "hint": "A mythical fire-breathing creature" },
  { "word": "flower", "hint": "A blooming plant" },
  { "word": "superhero", "hint": "Fights bad guys" },
  { "word": "kitten", "hint": "A baby cat" },
  { "word": "popcorn", "hint": "A movie-time snack" },
  { "word": "watermelon", "hint": "Big fruit with red flesh" },
  { "word": "jungle", "hint": "A dense forest" },
  { "word": "circus", "hint": "Clowns and acrobats perform here" },
  { "word": "alarm", "hint": "Wakes you up" },
  { "word": "pillow", "hint": "Soft item to sleep on" },
  { "word": "cactus", "hint": "A desert plant" },
  { "word": "snowman", "hint": "Made of snow" },
  { "word": "pizza", "hint": "Round food with toppings" },
  { "word": "snack", "hint": "Light food to munch on" },
  { "word": "starfish", "hint": "A star-shaped sea creature" },
  { "word": "camera", "hint": "Used to take photos" },
  { "word": "penguin", "hint": "A bird that cannot fly" },
  { "word": "glitter", "hint": "Shiny little sparkles" },
  { "word": "lollipop", "hint": "Candy on a stick" },
  { "word": "firefly", "hint": "A glowing insect" },
  { "word": "marble", "hint": "A round toy" },
  { "word": "island", "hint": "Land surrounded by water" },
  { "word": "spaceship", "hint": "Travels into space" },
  { "word": "cup", "hint": "Used to drink liquids" },
  { "word": "rabbit", "hint": "A fast-hopping animal" },
  { "word": "mirror", "hint": "Shows your reflection" },
  { "word": "beach", "hint": "Sandy area near the sea" },
  { "word": "tiger", "hint": "A big striped cat" },
  { "word": "roller", "hint": "Something that rolls" },
  { "word": "carrot", "hint": "An orange vegetable" },
  { "word": "moon", "hint": "Visible in the night sky" },
  { "word": "whistle", "hint": "Makes a sharp sound" },
  { "word": "lamp", "hint": "Provides light" },
  { "word": "wifi", "hint": "Used for wireless internet" },
  { "word": "android", "hint": "Mobile operating system" },
  { "word": "python", "hint": "Popular programming language" },
  { "word": "github", "hint": "Hosting platform for code" },
  { "word": "server", "hint": "Stores and manages data" },
  { "word": "laptop", "hint": "Portable computer" },
  { "word": "mobile", "hint": "Handheld smart device" },
  { "word": "browser", "hint": "Used to surf the internet" },
  { "word": "router", "hint": "Device that gives network connection" },
  { "word": "java", "hint": "Programming language" },
  { "word": "app", "hint": "Software on your phone" },
  { "word": "keyboard", "hint": "Used to type" },
  { "word": "email", "hint": "Online message service" },
  { "word": "screen", "hint": "Displays visuals" },
  { "word": "charger", "hint": "Powers your device" },
  { "word": "speaker", "hint": "Plays loud audio" },
  { "word": "blanket", "hint": "Keeps you warm" },
  { "word": "candle", "hint": "Used for light or decoration" },
  { "word": "toy", "hint": "Kids play with it" },
  { "word": "bottle", "hint": "Holds water" },
  { "word": "chair", "hint": "You sit on it" },
  { "word": "frame", "hint": "Displays a picture" },
  { "word": "paint", "hint": "Used to color" },
  { "word": "sticker", "hint": "Adhesive decoration" },
  { "word": "umbrella", "hint": "Used in rain" },
  { "word": "train", "hint": "Moves on tracks" },
  { "word": "shoe", "hint": "Worn on feet" },
  { "word": "clock", "hint": "Shows time" },
  { "word": "basket", "hint": "Used to carry items" },
  { "word": "soap", "hint": "Used for cleaning" },
  { "word": "flowerpot", "hint": "Holds a plant" },
  { "word": "sparrow", "hint": "A small bird" },
  { "word": "puzzle", "hint": "Something that needs thinking to solve" },
  { "word": "logic", "hint": "Used to make smart decisions" },
  { "word": "memory", "hint": "Ability to remember things" },
  { "word": "pattern", "hint": "A repeated design or sequence" },
  { "word": "riddle", "hint": "A tricky question with a clever answer" },
  { "word": "brain", "hint": "Controls your thinking" },
  { "word": "focus", "hint": "Paying close attention" },
  { "word": "answer", "hint": "Solution to a question" },
  { "word": "idea", "hint": "A thought or plan" },
  { "word": "quiz", "hint": "A test of knowledge" }
];